name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Run tests
        run: |
          pnpm run test:ci
