name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Run tests
        run: |
          pnpm run test:ci
